export const phrases = [
  "What else about today stands out to you? Add another entry to your story.",
  "The universe is still listening — what’s one more moment you’d like to share?",
  "Your day has many layers. What’s another one you’d like to capture?",
  "Is there a thought or feeling from today that’s still on your mind? Write it down.",
  "Another moment worth remembering? Add it here before the day slips away.",
  "What’s one more thing the universe should know about your day?",
  "Every entry makes your story richer — what else can you share from today?",
  "Did something else happen today that you’d like to hold onto? Write it down.",
  "Reflecting a bit more could bring clarity. What else is on your mind about today?",
  "The little things matter too. Add another entry to capture them.",
  "Your day isn’t fully told yet — what’s another piece of the puzzle?",
  "What’s one more thought, memory, or feeling you’d like to record?",
  "The universe is always here to listen — what else can you share about today?",
  "Another entry could help you see your day in a new light. What’s next?",
  "Capture another moment before it fades — what else happened today?",
  "Your day has a story to tell. What’s another chapter you can add now?",
  "Even the quiet moments are worth noting. What else stands out to you?",
  "There’s always more to your story. What’s another piece you’d like to share?",
  "What’s another feeling or thought you’d like to let out before the day ends?",
  "Your day is unique — what’s another moment that made it special?",
  "Don’t let a memory slip away. Add one more thought, image, or reflection.",
  "Another entry can help you remember the little joys or challenges of today.",
  "What’s one more thing you’d tell the universe about today if you could?",
  "Your day has so many moments to explore. What’s another one worth writing about?",
  "Every entry counts. What’s another memory, feeling, or thought you can add?",
  "The universe loves hearing from you — what else can you share from today?",
  "What’s another experience from today that shaped how you’re feeling now?",
  "Take a moment to pause — what else would you like to reflect on about today?",
  "What’s another part of today’s story you’d like to keep for yourself?",
  "Even if it seems small, every moment matters. What’s one more thing from today?",
  "What’s a new perspective or insight you gained today? Share it here.",
  "You’ve already shared so much — what’s one more memory to add to the mix?",
  "What’s another moment that deserves to be part of your story today?",
  "Think back — what’s one more thing from today that made you feel something?",
  "The universe loves the details. What’s another one you’d like to add?",
  "Your day isn’t over yet. What’s one more entry you’d like to make?",
];
