export const phrases = [
  "Hello Universe, today was filled with moments of...",
  "Dear Universe, I woke up feeling...",
  "Universe, I felt grateful for so many things today, especially...",
  "Today began with a thought, dear Universe, and that thought was...",
  "Universe, today brought me closer to...",
  "I want to share with you, Universe, that I experienced...",
  "Something unexpected happened today, Universe, and it was...",
  "Today I discovered, Universe, that life is full of...",
  "I’m feeling this way today, Universe:...",
  "Universe, the highlight of my day was definitely...",
  "Let me tell you, Universe, that today I found comfort in...",
  "Universe, today’s journey started with a simple...",
  "Universe, I was caught off guard by a moment of...",
  "Thank you, Universe, for showing me the beauty of...",
  "Today I paused for a moment, Universe, and noticed how...",
  "Universe, I couldn’t stop thinking about the way...",
  "Something about today reminded me, Universe, of the importance of...",
  "Universe, I’m proud of myself for taking the time to...",
  "I felt a deep connection today, Universe, when I encountered...",
  "A beautiful moment I want to share, Universe, was when I saw...",
  "Universe, today’s challenge tested me, but I learned...",
  "I found inspiration today, Universe, in the simple act of...",
  "I’m excited to tell you, Universe, that I’m looking forward to...",
  "My heart felt lighter today, Universe, when I let go of...",
  "Universe, I felt connected to others when I shared...",
  "Today felt like an adventure, Universe, starting with...",
  "I found a peaceful moment today, Universe, while I was...",
  "Universe, today brought me clarity about...",
  "I want to remember this moment, Universe, because it taught me...",
  "The best part of today, Universe, was when I realized...",
  "Today was a reminder, Universe, that life can be about...",
  "Universe, I felt surrounded by beauty when I noticed...",
  "Today made me think about the way, Universe, that small actions can...",
  "I want to thank you, Universe, for helping me find joy in...",
  "Universe, I faced a tough decision today, and I realized...",
  "A moment of peace today, Universe, came when I stopped to...",
  "Dear Universe, I saw kindness in the way that...",
  "Universe, today I felt brave when I decided to...",
  "I noticed something wonderful today, Universe:...",
  "Today was a day of learning, Universe, because I finally understood...",
  "I want to ask you, Universe, for the strength to keep pursuing...",
  "Universe, I felt like everything aligned perfectly when...",
  "Today I was reminded, Universe, that love can be found in...",
  "I want to cherish this memory, Universe, of how I spent time with...",
  "Dear Universe, I overcame a fear today by...",
  "Universe, I realized today that I need more of...",
  "I’m grateful, Universe, for the chance to reflect on...",
  "Universe, I want to express my gratitude for the support I felt from...",
  "Today taught me, Universe, that even in struggles there is...",
  "Universe, I felt joy today in the quiet moment of...",
  "I want to share with you, Universe, that I’m learning to embrace...",
  "Dear Universe, I ended the day feeling inspired by...",
  "Today brought me unexpected happiness, Universe, when I saw...",
];
